Fix for vite 8 rolldown integration breaking change with strict type checking for moduleSideEffects value
`moduleSideEffects` cannot return a number (this sometimes would return `0` which breaks rolldown).

```
Error: Value is none of these types `bool`, `String`,  on BindingHookTransformOutput.moduleSideEffects
```